name: Build And deploy application
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get into server and run deployScript
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd gh-actions-cicd
          git pull
          export NVM_DIR="$HOME/.nvm"
          [-s "$NVM_DIR/nvm.sh"] && \. "$NVM_DIR/nvm.sh"
          npm install
          pm2 restart app
          echo Completed
